import {
  PlatformKPIs,
  HospitalKPIs,
  Hospital,
  Doctor,
  Patient,
  Appointment,
  AIConversation,
  EHROperation,
  Workflow,
  AuditEvent,
  Questionnaire,
  QuestionnaireResponse,
  Notification,
} from "@/types";

// ===== Platform KPIs =====
export const mockPlatformKPIs: PlatformKPIs = {
  total_hospitals: 42,
  active_hospitals: 38,
  total_doctors: 864,
  total_patients: 18420,
  appointments_today: 1243,
  ai_calls_today: 1817,
  booking_success_rate: 94.2,
  questionnaire_completion_rate: 88.7,
  human_escalation_rate: 4.1,
  avg_ai_latency: 1.4,
  ehr_integration_success_rate: 97.8,
};

export const mockHospitalKPIs: HospitalKPIs = {
  appointments_today: 47,
  upcoming_appointments: 156,
  active_doctors: 23,
  available_slots: 312,
  cancelled_appointments: 5,
  rescheduled_appointments: 8,
  ai_bookings: 34,
  human_escalations: 2,
  questionnaire_completion: 91.3,
  workflow_failures: 1,
  ehr_success_rate: 98.2,
  ehr_failure_count: 2,
};

// ===== Hospitals =====
export const mockHospitals: Hospital[] = [
  {
    id: "h1",
    name: "City General Hospital",
    address: "123 Medical Drive",
    city: "Hyderabad",
    state: "Telangana",
    phone: "+91-40-12345678",
    email: "admin@citygeneral.com",
    website: "https://citygeneral.com",
    status: "approved",
    departments: ["Cardiology", "Orthopedics", "Neurology", "Pediatrics"],
    specialties: ["Cardiology", "Orthopedics", "Neurology", "Pediatrics", "General Medicine"],
    tenant_id: "t1",
    created_at: "2024-01-15T10:00:00Z",
    updated_at: "2024-06-10T14:30:00Z",
  },
  {
    id: "h2",
    name: "Care Hospital",
    address: "456 Healthcare Blvd",
    city: "Bangalore",
    state: "Karnataka",
    phone: "+91-80-87654321",
    email: "admin@carehospital.com",
    status: "approved",
    departments: ["Dermatology", "Oncology", "Gastroenterology"],
    specialties: ["Dermatology", "Oncology", "Gastroenterology", "General Medicine"],
    tenant_id: "t2",
    created_at: "2024-02-20T09:00:00Z",
    updated_at: "2024-05-15T16:00:00Z",
  },
  {
    id: "h3",
    name: "LifeLine Medical Center",
    address: "789 Wellness Ave",
    city: "Chennai",
    state: "Tamil Nadu",
    phone: "+91-44-11223344",
    email: "info@lifelinemc.com",
    status: "submitted",
    departments: ["Pulmonology", "Endocrinology"],
    specialties: ["Pulmonology", "Endocrinology"],
    tenant_id: "t3",
    created_at: "2024-09-01T12:00:00Z",
    updated_at: "2024-09-01T12:00:00Z",
  },
  {
    id: "h4",
    name: "MedPlus Clinic",
    address: "321 Health St",
    city: "Mumbai",
    state: "Maharashtra",
    phone: "+91-22-55667788",
    email: "contact@medplus.in",
    status: "under_review",
    departments: ["Psychiatry", "Ophthalmology"],
    specialties: ["Psychiatry", "Ophthalmology"],
    tenant_id: "t4",
    created_at: "2024-08-20T08:00:00Z",
    updated_at: "2024-08-25T10:00:00Z",
  },
];

// ===== Doctors =====
export const mockDoctors: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Arun Sharma",
    email: "arun.sharma@citygeneral.com",
    photo_url: "",
    specialty: "Cardiology",
    department: "Cardiology",
    qualifications: ["MBBS", "MD", "DM Cardiology"],
    experience_years: 15,
    languages: ["English", "Hindi", "Telugu"],
    consultation_types: ["Hospital Visit", "Online"],
    consultation_duration: 30,
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    status: "active",
    created_at: "2024-01-20T10:00:00Z",
  },
  {
    id: "d2",
    name: "Dr. Priya Rao",
    email: "priya.rao@citygeneral.com",
    specialty: "Orthopedics",
    department: "Orthopedics",
    qualifications: ["MBBS", "MS Orthopedics"],
    experience_years: 12,
    languages: ["English", "Hindi", "Kannada"],
    consultation_types: ["Hospital Visit"],
    consultation_duration: 20,
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    status: "active",
    created_at: "2024-02-01T10:00:00Z",
  },
  {
    id: "d3",
    name: "Dr. Rahul Mehta",
    email: "rahul.mehta@carehospital.com",
    specialty: "Dermatology",
    department: "Dermatology",
    qualifications: ["MBBS", "MD Dermatology"],
    experience_years: 8,
    languages: ["English", "Hindi"],
    consultation_types: ["Hospital Visit", "Online", "Follow-up"],
    consultation_duration: 15,
    hospital_id: "h2",
    hospital_name: "Care Hospital",
    status: "active",
    created_at: "2024-03-01T10:00:00Z",
  },
  {
    id: "d4",
    name: "Dr. Sneha Iyer",
    email: "sneha.iyer@citygeneral.com",
    specialty: "Neurology",
    department: "Neurology",
    qualifications: ["MBBS", "DM Neurology"],
    experience_years: 10,
    languages: ["English", "Tamil", "Hindi"],
    consultation_types: ["Hospital Visit"],
    consultation_duration: 30,
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    status: "inactive",
    created_at: "2024-04-01T10:00:00Z",
  },
];

// ===== Patients =====
export const mockPatients: Patient[] = [
  { id: "p1", name: "Ravi Kumar", email: "ravi@email.com", phone: "+91-9876543210", date_of_birth: "1990-05-15", preferred_communication: "email", created_at: "2024-03-01T10:00:00Z" },
  { id: "p2", name: "Anita Singh", email: "anita@email.com", phone: "+91-9876543211", date_of_birth: "1985-08-22", preferred_communication: "phone", created_at: "2024-03-05T10:00:00Z" },
  { id: "p3", name: "Vikram Reddy", email: "vikram@email.com", phone: "+91-9876543212", date_of_birth: "1978-12-10", preferred_communication: "email", created_at: "2024-04-01T10:00:00Z" },
  { id: "p4", name: "Deepa Nair", email: "deepa@email.com", phone: "+91-9876543213", date_of_birth: "1995-02-28", preferred_communication: "sms", created_at: "2024-05-01T10:00:00Z" },
];

// ===== Appointments =====
export const mockAppointments: Appointment[] = [
  {
    id: "apt1",
    patient_id: "p1",
    patient_name: "Ravi Kumar",
    doctor_id: "d1",
    doctor_name: "Dr. Arun Sharma",
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    specialty: "Cardiology",
    appointment_type: "Hospital Visit",
    date: "2024-09-15",
    time: "10:00",
    duration: 30,
    status: "confirmed",
    external_appointment_id: "EHR-88421",
    ehr_sync_status: "verified",
    questionnaire_status: "completed",
    created_at: "2024-09-10T14:00:00Z",
  },
  {
    id: "apt2",
    patient_id: "p2",
    patient_name: "Anita Singh",
    doctor_id: "d2",
    doctor_name: "Dr. Priya Rao",
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    specialty: "Orthopedics",
    appointment_type: "Hospital Visit",
    date: "2024-09-15",
    time: "11:30",
    duration: 20,
    status: "confirmed",
    ehr_sync_status: "verified",
    questionnaire_status: "pending",
    created_at: "2024-09-11T09:00:00Z",
  },
  {
    id: "apt3",
    patient_id: "p3",
    patient_name: "Vikram Reddy",
    doctor_id: "d3",
    doctor_name: "Dr. Rahul Mehta",
    hospital_id: "h2",
    hospital_name: "Care Hospital",
    specialty: "Dermatology",
    appointment_type: "Online",
    date: "2024-09-16",
    time: "14:00",
    duration: 15,
    status: "pending",
    questionnaire_status: "pending",
    created_at: "2024-09-12T16:00:00Z",
  },
  {
    id: "apt4",
    patient_id: "p4",
    patient_name: "Deepa Nair",
    doctor_id: "d1",
    doctor_name: "Dr. Arun Sharma",
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    specialty: "Cardiology",
    appointment_type: "Follow-up",
    date: "2024-09-14",
    time: "15:30",
    duration: 30,
    status: "completed",
    external_appointment_id: "EHR-88435",
    ehr_sync_status: "verified",
    questionnaire_status: "completed",
    created_at: "2024-09-08T11:00:00Z",
  },
  {
    id: "apt5",
    patient_id: "p1",
    patient_name: "Ravi Kumar",
    doctor_id: "d2",
    doctor_name: "Dr. Priya Rao",
    hospital_id: "h1",
    hospital_name: "City General Hospital",
    specialty: "Orthopedics",
    appointment_type: "Hospital Visit",
    date: "2024-09-17",
    time: "09:00",
    duration: 20,
    status: "cancelled",
    created_at: "2024-09-09T10:00:00Z",
  },
];

// ===== AI Conversations =====
export const mockAIConversations: AIConversation[] = [
  {
    id: "conv1",
    patient_id: "p1",
    patient_name: "Ravi Kumar",
    channel: "web_voice",
    started_at: "2024-09-10T14:00:00Z",
    ended_at: "2024-09-10T14:04:32Z",
    duration_seconds: 272,
    intents_detected: ["book_appointment"],
    capabilities_used: ["search_doctors", "check_availability", "create_appointment"],
    outcome: "Appointment booked successfully",
    escalated: false,
  },
  {
    id: "conv2",
    patient_id: "p2",
    patient_name: "Anita Singh",
    channel: "phone",
    started_at: "2024-09-11T09:00:00Z",
    ended_at: "2024-09-11T09:06:15Z",
    duration_seconds: 375,
    intents_detected: ["book_appointment", "questionnaire"],
    capabilities_used: ["search_doctors", "check_availability", "create_appointment", "get_questionnaire"],
    outcome: "Appointment booked + questionnaire started",
    escalated: false,
  },
  {
    id: "conv3",
    patient_id: "p3",
    patient_name: "Vikram Reddy",
    channel: "web_voice",
    started_at: "2024-09-12T16:00:00Z",
    ended_at: "2024-09-12T16:08:45Z",
    duration_seconds: 525,
    intents_detected: ["book_appointment"],
    capabilities_used: ["search_doctors", "check_availability"],
    outcome: "Escalated to human support",
    escalated: true,
  },
];

// ===== EHR Operations =====
export const mockEHROperations: EHROperation[] = [
  { id: "ehr1", hospital_id: "h1", hospital_name: "City General Hospital", operation_type: "create_appointment", connector: "medplum_fhir", external_id: "EHR-88421", status: "success", verification_status: "verified", duration_ms: 1240, retries: 0, created_at: "2024-09-10T14:02:00Z" },
  { id: "ehr2", hospital_id: "h1", hospital_name: "City General Hospital", operation_type: "create_appointment", connector: "medplum_fhir", external_id: "EHR-88435", status: "success", verification_status: "verified", duration_ms: 980, retries: 0, created_at: "2024-09-08T11:01:00Z" },
  { id: "ehr3", hospital_id: "h2", hospital_name: "Care Hospital", operation_type: "create_appointment", connector: "mock_ehr", status: "failure", verification_status: "failed", duration_ms: 5020, error: "Connection timeout", retries: 3, created_at: "2024-09-12T16:05:00Z" },
  { id: "ehr4", hospital_id: "h1", hospital_name: "City General Hospital", operation_type: "cancel_appointment", connector: "medplum_fhir", external_id: "EHR-88410", status: "success", verification_status: "verified", duration_ms: 650, retries: 0, created_at: "2024-09-09T10:02:00Z" },
];

// ===== Workflows =====
export const mockWorkflows: Workflow[] = [
  { id: "wf1", type: "appointment_confirmation", status: "completed", trigger: "appointment_booked", related_id: "apt1", started_at: "2024-09-10T14:02:30Z", completed_at: "2024-09-10T14:02:45Z", retries: 0 },
  { id: "wf2", type: "questionnaire_reminder", status: "running", trigger: "questionnaire_pending", related_id: "apt2", started_at: "2024-09-11T09:05:00Z", retries: 0 },
  { id: "wf3", type: "ehr_sync_retry", status: "failed", trigger: "ehr_integration_failed", related_id: "ehr3", started_at: "2024-09-12T16:06:00Z", completed_at: "2024-09-12T16:10:00Z", error: "Max retries exceeded", retries: 3 },
  { id: "wf4", type: "appointment_reminder", status: "completed", trigger: "scheduled", related_id: "apt4", started_at: "2024-09-14T08:00:00Z", completed_at: "2024-09-14T08:00:15Z", retries: 0 },
];

// ===== Audit Events =====
export const mockAuditEvents: AuditEvent[] = [
  { id: "ae1", event_type: "APPOINTMENT_BOOKED", actor_id: "p1", actor_name: "AI Agent", actor_role: "patient", resource_type: "appointment", resource_id: "apt1", correlation_id: "corr-001", timestamp: "2024-09-10T14:02:00Z" },
  { id: "ae2", event_type: "EHR_SYNC_VERIFIED", actor_id: "system", actor_name: "System", actor_role: "platform_admin", resource_type: "ehr_operation", resource_id: "ehr1", correlation_id: "corr-001", timestamp: "2024-09-10T14:02:30Z" },
  { id: "ae3", event_type: "QUESTIONNAIRE_COMPLETED", actor_id: "p1", actor_name: "Ravi Kumar", actor_role: "patient", resource_type: "questionnaire_response", resource_id: "qr1", correlation_id: "corr-001", timestamp: "2024-09-10T14:04:00Z" },
  { id: "ae4", event_type: "APPOINTMENT_CANCELLED", actor_id: "p1", actor_name: "Ravi Kumar", actor_role: "patient", resource_type: "appointment", resource_id: "apt5", correlation_id: "corr-002", timestamp: "2024-09-09T10:01:00Z" },
  { id: "ae5", event_type: "HOSPITAL_APPROVED", actor_id: "admin1", actor_name: "Platform Admin", actor_role: "platform_admin", resource_type: "hospital", resource_id: "h1", timestamp: "2024-01-15T11:00:00Z" },
  { id: "ae6", event_type: "HUMAN_ESCALATION_TRIGGERED", actor_id: "system", actor_name: "AI Agent", actor_role: "patient", resource_type: "conversation", resource_id: "conv3", correlation_id: "corr-003", timestamp: "2024-09-12T16:08:00Z" },
];

// ===== Questionnaires =====
export const mockQuestionnaires: Questionnaire[] = [
  {
    id: "q1",
    title: "Cardiology Pre-Visit Assessment",
    specialty: "Cardiology",
    doctor_id: "d1",
    status: "active",
    questions: [
      { id: "q1_1", text: "Have you experienced chest discomfort recently?", type: "yes_no", required: true, order: 1 },
      { id: "q1_2", text: "When did the symptoms begin?", type: "short_text", required: true, order: 2 },
      { id: "q1_3", text: "Does it occur during physical activity?", type: "yes_no", required: true, order: 3 },
      { id: "q1_4", text: "Are you currently taking any prescribed medication?", type: "yes_no", required: true, order: 4 },
      { id: "q1_5", text: "Rate your pain level (1-10)", type: "numeric", required: false, order: 5 },
    ],
    created_at: "2024-01-25T10:00:00Z",
  },
];

export const mockQuestionnaireResponses: QuestionnaireResponse[] = [
  {
    id: "qr1",
    questionnaire_id: "q1",
    appointment_id: "apt1",
    patient_id: "p1",
    patient_name: "Ravi Kumar",
    responses: {
      q1_1: true,
      q1_2: "About two weeks ago",
      q1_3: true,
      q1_4: false,
      q1_5: 6,
    },
    status: "completed",
    completed_at: "2024-09-10T14:04:00Z",
  },
];

// ===== Notifications =====
export const mockNotifications: Notification[] = [
  { id: "n1", user_id: "admin1", type: "hospital_application", title: "New Hospital Application", message: "LifeLine Medical Center has submitted a registration application", read: false, created_at: "2024-09-13T10:00:00Z" },
  { id: "n2", user_id: "admin1", type: "ehr_failure", title: "EHR Integration Failed", message: "Care Hospital: Connection timeout during appointment creation", read: false, created_at: "2024-09-12T16:05:00Z" },
  { id: "n3", user_id: "admin1", type: "escalation", title: "Human Escalation", message: "Patient Vikram Reddy's conversation was escalated to human support", read: true, created_at: "2024-09-12T16:08:00Z" },
];

// ===== Analytics Time Series (for charts) =====
export const mockAppointmentsTrend = [
  { date: "Sep 1", count: 42, ai_booked: 38 },
  { date: "Sep 2", count: 38, ai_booked: 35 },
  { date: "Sep 3", count: 55, ai_booked: 50 },
  { date: "Sep 4", count: 47, ai_booked: 44 },
  { date: "Sep 5", count: 63, ai_booked: 58 },
  { date: "Sep 6", count: 51, ai_booked: 47 },
  { date: "Sep 7", count: 29, ai_booked: 26 },
  { date: "Sep 8", count: 44, ai_booked: 40 },
  { date: "Sep 9", count: 52, ai_booked: 48 },
  { date: "Sep 10", count: 61, ai_booked: 57 },
  { date: "Sep 11", count: 58, ai_booked: 54 },
  { date: "Sep 12", count: 49, ai_booked: 45 },
  { date: "Sep 13", count: 67, ai_booked: 63 },
  { date: "Sep 14", count: 43, ai_booked: 39 },
];

export const mockAILatencyTrend = [
  { date: "Sep 1", avg: 1.3, p95: 2.1 },
  { date: "Sep 2", avg: 1.4, p95: 2.3 },
  { date: "Sep 3", avg: 1.2, p95: 1.9 },
  { date: "Sep 4", avg: 1.5, p95: 2.4 },
  { date: "Sep 5", avg: 1.3, p95: 2.0 },
  { date: "Sep 6", avg: 1.4, p95: 2.2 },
  { date: "Sep 7", avg: 1.1, p95: 1.8 },
];

export const mockSpecialtyDistribution = [
  { name: "Cardiology", value: 28 },
  { name: "Orthopedics", value: 22 },
  { name: "Dermatology", value: 18 },
  { name: "Neurology", value: 14 },
  { name: "Pediatrics", value: 10 },
  { name: "General Medicine", value: 8 },
];
